### ISSUE TITLE
AR Idea Search(AR 아이디어 탐색)

### ISSUE THREAD

**Issue by SyingSHY** [SyingSHY/2301-IMP-AR#1]
# AR Idea Search(AR 아이디어 탐색)

이슈 코멘트에 본인이 생각한 AR 프로젝트 주제 아이디어를 적어주세요.

아이디어를 설명하는데 참고할만한 이미지나 동영상이 있으면 첨부 또는 링크해주세요.

**Comment by SyingSHY** [comment]
## AR 테이블탑 타이쿤

#### Motivation/background for your AR app (you can show some reference apps to explain your idea)

- 타이쿤류 게임들(ex. 롤러코스터 타이쿤)
- 동물의 숲
- 지난 IMP 프로젝트 중 테이블 평면 인식 게임들

#### Your idea shortly + key features

- 놀이공원/베이커리 등 컨셉 요소
- 손동작에 반응하는 시설들과 NPC들
- QR코드를 이용한 세이브 앤 로드 지원 & 테이블 넓이에 따른 자동 스케일 조정

#### Motivation for using AR in the app (why is AR needed for your app?)

- 2D 평면 상에서 벗어나 움직이면서 관찰하는 나의 타이쿤
- 강화된 상호작용

#### Schedule

- 3월 3주(3월 17일) : 
- 3월 4주(3월 24일) : 
- 3월 5주(3월 31일) :
- 4월 1주(4월 7일) :
- 4월 2주(4월 14일) : 
- 4월 3주(4월 21일) : 
- 4월 4주(4월 28일) : Final presentation(최종 발표)

#### Work division between team members

- 추후 결정

**Comment by zzogak** [comment]
Motivation/background for your AR app (you can show some reference apps to explain your idea)
-터치 앤 드래그 게임
-어린 시절에 응급 구조 플래시 게임을 재밌게 했던 것에서 영감 받았음.

Your idea shortly + key features
-카메라를 통해 방을 둘러보면 바닥에 사람이 누워있음.
-사람은 말풍선을 이용해 아픈 곳을 이야기하고 ui에서 아이콘을 드래그해 치료하는 방식

Motivation for using AR in the app (why is AR needed for your app?)
-응급 상황을 실제로 시뮬레이션 하며 대비하는 것은 쉽지 않으므로 가상 현실 공간에서 그것을 미리 준비하고자 함.

Schedule
3월 3주(3월 17일) : Idea meeting and work divisioning. (아이디어 미팅 및 역할 분배)
3월 4주(3월 24일) : Finding Assets for the project. (프로젝트를 위한 에셋 준비)
3월 5주(3월 31일) : Working Unity project (1) (유니티 프로젝트 작업)
4월 1주(4월 7일) : Working Unity project (2) (유니티 프로젝트 작업)
4월 2주(4월 14일) :  Finishing Unity project and meeting for making trailer (유니티 프로젝트 마무리 및 트레일러 제작 미팅)
4월 3주(4월 21일) : Making trailer. (트레일러 제작)
4월 4주(4월 28일) : Final presentation(최종 발표)

Work division between team members
양성호 : Project manager (프로젝트 매니저)
이동원 : Graphic and resource manager (그래픽 및 리소스 매니저)
신승우 : Trailer and presentation mangaer (트레일러및발표 매니저)
공준혁 : Ar design manager (AR 기획 매니저)

Every team member will also working on Unity programming together.

**Comment by rhdelife** [comment]
Motivation/background for your AR app (you can show some reference apps to explain your idea)

-pick up and use item game (like battle ground)
-비세라 클린업-Vicera Cleanup ( i have never done this game, but maybe  its ui &usage is similar my idea.)

Your idea shortly + key features
-각 스테이지 별로 다양한 얼룩들이 방 주변에 생길 것이다. 주어진 시간내에 청소도구를 이용하여 얼룩을 제거.
-카메라를 통해 방에 얼룩을 생성함
-도구들의 특성에 따라 청소가 쉬워짐

Motivation for using AR in the app (why is AR needed for your app?)

어린 아이들에게 직접 방을 어지럽히지 않더라도 청소방법에 대한 교육을 할 수 있다. 이 방법은 실제적이고 흥미롭다.
(You can teach young children how to clean without messing up their room yourself. This method is practical and interesting.)

Schedule
3월 3주(3월 17일) : Select the Idea and materialize idea (아이디어 선정 및 아이디어 구체화)
3월 4주(3월 24일) :  Finding Assets for the project and finding function & tool for project (필요 에셋 준비 및 구현 방법 탐색)
3월 5주(3월 31일) : Working on Unity project(1) (유니티 프로젝트 작업)
4월 1주(4월 7일) : Working on Unity project(1) (유니티 프로젝트 작업)
4월 2주(4월 14일) : Finishing Unity project and meeting for making trailer (유니티 프로젝트 마무리 및 트레일러 제작 미팅)
4월 3주(4월 21일) : Making trailer and final check ( 트레일러 제작 및 최종 점검)
4월 4주(4월 28일) : Final presentation(최종 발표)
Work division between team members
양성호 : Project manager (프로젝트 매니저)
이동원 : Graphic and resource (그래픽 및 리소스)
신승우 : Trailer and presentation (트레일러및발표)
공준혁 : Ar designing (AR 기획)

Whole team member will also working on Unity programming together .( 전 멤버 유니티 프로그래밍 공동 작업 예정)

**Comment by rhdelife** [comment]
Game workflow (게임 진행 흐름)

First entrance phase → Stage selection phase → Gameplay phase → Play result phase
최초 진입 단계 → 스테이지 선택 단계 → 게임 플레이 단계 → 플레이 결과 단계

Main features (각 단계별 주요 기능)

최초 진입 화면
Game title(게임 타이틀)
Start button(게임 시작 버튼)
Exit button(게임 종료 버튼)
스테이지 선택 화면
Stage list & button (스테이지 목록 & 버튼)
Find ball(공 에셋 찾기)
게임 플레이 화면
Pause button (일시정지 버튼)

플레이 결과 화면
Score panel (점수 패널)
Required assets (필요 에셋)

각종 공 텍스쳐, 볼링 핀, 다트, 골대
Required scripts

Stain random generation script (공 생성 스크립트)

Planes(walls and floors) detection script (평면(벽 또는 바닥) 인식 스크립트)
[Not certain] Hand motion recognition script ([미정] 손 동작 인식 스크립트)
