### ISSUE TITLE
AR project item detailing (AR 프로젝트 아이템 구체화)

### ISSUE THREAD

**Issue by SyingSHY** [SyingSHY/2301-IMP-AR#2]
### Game workflow (게임 진행 흐름)

First entrance phase &rarr; Stage selection phase &rarr; Gameplay phase &rarr; Play result phase   
최초 진입 단계 &rarr; 스테이지 선택 단계 &rarr; 게임 플레이 단계 &rarr; 플레이 결과 단계

### Main features (각 단계별 주요 기능)

1. 최초 진입 화면
 + Game title(게임 타이틀)
 + Start button(게임 시작 버튼)
 + Exit button(게임 종료 버튼)
2. 스테이지 선택 화면
 + Stage list & button (스테이지 목록 & 버튼)
 + Game start button (게임 시작 버튼)
3. 게임 플레이 화면
 + Pause button (일시정지 버튼)
 + Cleaning item list (청소도구 아이템 목록) : If click, hand-held item changes. (클릭하면, 손에 든 아이템 변화)
 + When clicks stain in screen, opens information panel of touched stain. (화면을 통해 대상 클릭 시, 대상의 정보 패널 오픈)
4. 플레이 결과 화면
 + Score panel (점수 패널)

### Required assets (필요 에셋)

- Stain : 다양한 얼룩 물때, 기름 때, 음식 얼룩, 먼지 ...
- Hard target : 눌러 붙은 껌(껌 칼 + 융해제) ...
- Tool : 분무기, 청소기, 수세미 등 ...
- Button : 각종 단계별 기능을 위한 버튼들

### Required scripts

- Stain random generation script (오염물 랜덤 생성 스크립트)
- Planes(walls and floors) detection script (평면(벽 또는 바닥) 인식 스크립트)
- [Not certain] Hand motion recognition script ([미정] 손 동작 인식 스크립트)

**Comment by rhdelife** [comment]
필요 에셋

stain : 다양한 얼룩  물 떼, 기름 떼, 음식 얼룩, 먼지
tool :  분무기, 청소기 , 수세미 , 등...

**Comment by zzogak** [comment]
기획에 대한 코멘트:

다른 팀들 중에서 우리와 비슷하게 청소 AR 앱을 만들겠다는 팀이 있었습니다. 

그 팀도 하다보면 변하겠지만, 프레젠테이션에 나온 아이디어는 

"얼룩을 쏘는 대포가 있고 벽에 묻은 얼룩을 치우는 게임" 이었던 걸로 기억합니다.

우리는 "아이들의 교육"이라는 다른 동기가 있으니 그것을 강조하는 방향으로 개발하는 것도 좋을 것 같습니다.

에셋에 대한 코멘트 : 

https://assetstore.unity.com/packages/3d/props/industrial/industrial-vacuum-cleaner-74888 무료 청소기 에셋

https://assetstore.unity.com/packages/3d/props/tools/maker-tool-set-diy-crafting-tools-229780 무료 분무기 등 모음 에셋

...

무료 에셋을 다운받아 매터리얼이나 텍스처를 수정하면서 그래픽을 구현할 생각입니다. 하지만 그래픽 에셋간의 분위기가 이질적이라면 3D 오브젝트를 이용해 에셋을 직접 만들어야 할 수도 있습니다.

**Comment by rhdelife** [comment]
제가 생각해봤는데 이번에 저희 팀과 유사한 컨셉으로 프로젝트를 진행하려는 팀이 있기도 하고 
만약 우리가 구현하고자 하는 방향대로 ar의 구현이 어려울 경우도 있으니   아직 늦지 않았으니 
기획을 다르게 해보는 것도 좋을 것 같다라고 생각했습니다. 
우리가 배운것을 활용하여 비교적 간단하면서도 창의적으로 만들 수 있는 것이 무엇이 있는지 고민하다가. 
방구석 운동선수라는 컨셉으로 하여 다양한 골대와 타깃이 화면에서 지형에 맞게 생기면 
해당 종목에 맞게 (축구, 농구 볼링) 의 공을 작동시켜 골을 넣는 것입니다. 
이 경우에는 아마 이전 프로젝트보다 어셋을 찾기에도 수월할 것 같습니다. 
팀원분들도 이 부분에 대해서 어떻게 생각하시는지 편하게 의견 남겨주시면 감사하겠습니다.


방구석

**Comment by 21070-LDW** [comment]
> 방구석
말씀해주신 아이디어는 저는 꽤 괜찮은 것 같습니다. 그런데  언급하신 것처럼 저희가 아직 ar에 대해서 구체적으로 배운 것이 없어서 구현에 적합한 아이디어가 무엇인지 판단하기가 조금 힘든 점은 있는 것 같습니다. 저는 어느 아이디어로 정해도 상관 없을 것 같긴 한데 만약 운동선수를 컨셉으로 한다면 기존에 아이들의 청소교육 처럼 구체적인 동기(ex: 진로 체험, 실내에서 가능한 운동 등)가 있으면 좋을 것 같고 골대나 타깃의 생성 알고리즘 (고정된 장소에서 생성 or 랜덤한 장소 or 원하는 곳 장소 선택 )등을 고민해 보면 좋을 것 같습니다. 아직 초기 단계라 저도 다른 아이디어가 없을지 고민해보겠습니다!

**Comment by SyingSHY** [comment]
@rhdelife
말씀해주신대로 에셋을 찾기에는 훨씬 수월할 것 같은데 승우님(@21070-LDW)이 언급해주신 것처럼 현재 주제에 구체적인 동기가 있는 점과 새로 제안해 주신 주제에 AR이 필요한 이유에 대해 의문점이 남아서 개인적으로 현재 주제가 좀 더 마음이 쏠립니다. 앞으로도 계속 생각해 보겠습니다!

**Comment by SyingSHY** [comment]
이번 주 수업 내용을 보면 귀찮고 어려울거라 생각되었던 많은 부분들을 유니티가 자체적으로 해결해주는 것으로 보입니다. 그래서 복잡하고 어려운 기능도 시간 투자해서 구글링하고 직접 들이받아 보면 충분히 가능할 것 같습니다. 기능 구현의 쉽고 어려움은 생각하지 말고 일단 재밌을 것 같거나 흥미롭겠다 싶은 기능들을 계속 제안해주세요!

## 게임 구조 제안

 최대한 상황을 간략화 시켜서 방의 정확한 구조가 아닌, 단순히 벽면과 바닥면을 인식하게 하고 해당 수직-수평면에 맞춰 오염물을 배치하면 좋을 것 같습니다. 오염물은 평면 인식 후 해당 평면 위 랜덤한 위치에 출현 이펙트 이후 배치되도록 설계할 수 있을 것 같습니다. 이후 화면 터치를 통해 해당 오염물에 대한 정보를 획득하고, 가능하다면 손 모양 인식을 통해 도구를 손에 붙인 후 도구를 오염물에 닿게 하여 청소하게 할 수 있게 한다면 좋을 것 같습니다.

### 벽에 생길 수 있는 Dirty

- 기름때(시간 제한, 시간 초과 시 굳어서 추가 조치 필요)
    - 정상적인 방법 : (세제) - 닦아내기
    - 잘못된 방법 :
    - 반응없는 방법 : 집게
- 거미줄
    - 정상적인 방법 : 먼지털이(Best), 닦아내기, 쓸어내기
    - 잘못된 방법 :
    - 반응없는 방법 :
- 음식 국물(시간 제한, 시간 초과 시 흡수되어 제거 불가능)
    - 정상적인 방법 : 닦아내기
    - 잘못된 방법 :
    - 반응없는 방법 :

### 바닥에 생길 수 있는 Dirty

- 똥 덩어리
    - 정상적인 방법 : 덩어리 제거 - 흔적 소독 - 닦아내기
    - 잘못된 방법 :
        - 덩어리 제거 → 닦아내기 : 덩어리가 뭉개져버리기
        - 덩어리 제거 → 소독액 살포 : 덩어리 유지 + 주변으로 액체 생김
        - 덩어리 제거 → 먼지털이 : 먼지털이 오염, 앞으로 치는 곳마다 흔적 생김
    - 반응 없는 처리 :
- 눌러붙은 껌
    - 정상적인 방법 : 껌 칼 → 융해제 → 닦아내기
    - 잘못된 방법 :
        - 껌 칼 → 닦아내기, 먼지털이 : 껌에 붙어서 도구 상실
- 먼지덩어리
    - 정상적인 처리 : 먼지털이, 닦아내기(Best), 쓸어내기(Best)
    - 잘못된 처리 :
        - X → 분무기 : 물 고임
    - 반응없는 처리 : 집게

**Comment by 21070-LDW** [comment]
여러 오염물을 각각 다른 도구들로 청소하는 컨셉을 잘 나타낸 것 같아 괜찮은 것 같습니다! 저도 조금 의견 덧붙이자면 기름 떼는 굳었을 때 다른 후속 조치를 취하는 것도 괜찮지만 어떤 도구를 활용해야 할지 감이 안 잡혀서 차라리 더 많은 양의 세제를 뿌려야 하거나 더 많이 닦아내야 하는 식으로 구현하는 것도 괜찮을 것 같다고 생각했습니다. 아직 얘기하기엔 이른 것 같지만 혹시 점수나 라이프 시스템도 만들게 된다면 잘못된 방법으로 청소할 시 라이프포인트가 감소하거나 BEST 방법으로 청소했을 시 추가 점수를 주는 방향도 고려해볼 만한 것 같습니다.

**Comment by SyingSHY** [comment]
> 일단은 볼링 농구 축구 정도 생각을 해보았습니다
> 축구의 경우는 디텍션을 통해서 골대를 만드는 걸로 하고 앞에 반복적으로 좌우로 움직이는 적이 있도록 하는게 어떨까 싶습니다. 또 손가락으로 버튼을 한게 눌렀을떄는 왼쪽으로 두개는 오른쪽으로 가게 하여 타이밍에 맞추어 골대에 넣는 식으로 진행하면 좋을 것 같습니다.

- 좌우로 움직이는 골키퍼를 피해 타이밍에 맞추어 넣는 게임 &rarr; :+1: Good Idea 같음!
- 누른 손가락의 숫자에 따라 방향을 결정한다고 하셨는데, Raycast로 공을 누른 것을 식별하고 이후 슛 방향으로 드래그 &rarr; 스크린 좌표 Vector2를 AR좌표 Vector3로 대응시키는 것이 더 직관적일 것으로 생각됨
- 터치 숫자든, 드래그든, 화면 중앙을 목표 골대로 위치했을 때 해당 골대를 대상으로 선택하고, 선택되었음을 강조하는 기능 필요
- 골대가 수직면에서 생성될 것인지, 평면에서 생성될 것인지 결정 필요

> 농구의 경우는 포켓몬고 처럼 몬스터볼을 던지는 식으로 하면 좋을 것 같습니다.
> 화면에서 여러 어셋이 뜨는데 농구공을 넣어야만 골로 인정이 되도록 하면 어떨까 싶습니다. 

- 이 부분에 대해 좀 더 의견이 필요함
- 단순히 골대 방향만 맞추면 알아서 슛이 들어가도록 만들기 &rarr; 너무 심심할 수 있음
- 링과 백보드를 구분해서 링 안에 닿아야 골로 인정되도록 만들기 &rarr; 백보드 충돌 및 반사 판정, 링 골인 판정, 생성된 골대의 크기 등 고려해야 할 부분 많음

> 볼링역시 농구와 비슷하게 하는데 볼링핀을 놓는 것을 사용자가 선택할 수 있으면 좋겠다고 생각합니다.

- 개인적으로 사용자가 볼링핀 놓는 것을 선택한다는 부분이 이해가 잘 안됨
- 수요일에 추가적인 설명 부탁드립니다

> 전반적으로 공놀이의 진행들은 이렇게 되면 좋을 것 같다고 생각하고. 시작화면에서 오늘 배운 UI 툴을 통해 본인이 희망하는 공놀이를 선택하여 진행하는 식이 좋을 것 같습니다. 

- 한 스테이지에 여러가지가 등장하는 것이 아니라 한 스테이지는 한 가지 종류의 게임?
- 게임의 목표에 대한 내용 필요

> 추가적으로 골을 넣을때 소리가 나거나 군중 소리가 나게 사운드소스를 추가하면 보다 실감나는 게임 진행이 될 것 같습니다.

- 필요 에셋 목록
- [ ] 사운드 리소스 : 군중 환호성
- [ ] 사운드 리소스 : 득점 판정 사운드

> 하나를 추가하여 인당 하나의 게임을 진행해도 좋고 아니면 어차피 나중에 합치는 작업을 할 것이기 때문에 세개 중에서 각각의 기능들을 세부적으로 나누어 분담해도 좋을 것 같습니다.

- UI + 각각의 기초 기능 구현?

**Comment by SyingSHY** [comment]
새 주제로 진행하기로 결정되어 이전 주제 이슈를 닫습니다.
